name: SimpleWarp
main: net.rymate.SimpleWarp.SimpleWarpPlugin
version: 2.3
commands:
  warp:
    description: Teleports you to the warp specified
    usage: /warp <warpname>
    aliases: [w]
    permission: SimpleWarp.warp
  setwarp:
    description: Creates a new warp
    usage: /setwarp <warpname>
    aliases: [sw]
    permission: SimpleWarp.setwarp
  listwarps:
    description: Lists the warps
    usage: /listwarps
    aliases: [lw]
    permission: SimpleWarp.listwarps
  delwarp:
    description: Deletes a warp
    usage: /delwarp <warpame>
    aliases: [dw]
    permission: SimpleWarp.delwarp
  home:
    description: Teleports you to your home
    usage: /home
    aliases: [h]
    permission: SimpleWarp.home
  sethome:
    description: Sets your home
    usage: /sethome
    aliases: [sh]
    permission: SimpleWarp.sethome
  visithome:
    description: Visit another player's home
    usage: /visithome
    aliases: [vh]
    permission: SimpleWarp.visithome
  delwarp:
    description: Deletes your home
    usage: /delhome
    aliases: [dh]
    permission: SimpleWarp.delhome