name: SimpleWarp
main: net.rymate.SimpleWarp.SimpleWarpPlugin
version: 2.3
commands:
  warp:
    description: Teleports you to the warp specified
    usage: /warp <warpname>
    aliases: [w]
    permission: warp.go
  setwarp:
    description: Creates a new warp
    usage: /setwarp <warpname>
    aliases: [sw]
    permission: warp.set
  listwarps:
    description: Lists the warps
    usage: /listwarps
    aliases: [lw]
    permission: warp.list
  home:
    description: Teleports you to your home
    usage: /warp <warpname>
    aliases: [w]
    permission: home.go
  sethome:
    description: Sets your home
    usage: /setwarp <warpname>
    aliases: [sw]
    permission: home.set
  visithome:
    description: Visit another player's home
    usage: /visithome
    aliases: [vh]
    permission: home.visit

