name: SimpleWarp
main: net.rymate.SimpleWarp.SimpleWarpPlugin
version: 2.1
commands:
  warp:
    description: Teleports you to the warp specified
    usage: /warp <warpname>
    aliases: [w]
    permission: warp.set
  setwarp:
    description: Creates a new warp
    usage: /setwarp <warpname>
    aliases: [sw]
    permission: warp.go
  listwarps:
    description: Lists the warps
    usage: /listwarps
    aliases: [lw]
    permission: warp.list